# Generated by Django 5.0.4 on 2024-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Douyin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=20)),
                ('hotvalue', models.CharField(max_length=20)),
                ('label', models.IntegerField()),
                ('position', models.IntegerField()),
                ('sentenceid', models.CharField(max_length=20)),
                ('word', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'douyin',
                'managed': True,
            },
        ),
    ]
